default_agent: my_agent
agents:
  my_agent:
    name: my_agent
    entrypoint: my_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::083439127731:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e72c1a7c7a
      execution_role_auto_create: false
      account: 083439127731
      region: us-east-1
      ecr_repository: 083439127731.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-my_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: my_agent-6qs1kDEQkj
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:083439127731:runtime/my_agent-6qs1kDEQkj
      agent_session_id: 2a8dc406-0e4c-4c9e-b15e-835399d6eaac
    codebuild:
      project_name: bedrock-agentcore-my_agent-builder
      execution_role: arn:aws:iam::083439127731:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e72c1a7c7a
      source_bucket: bedrock-agentcore-codebuild-sources-083439127731-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
